//I plan to make it so that all of these arrays are concatenated when requested rather than being separate.
//You should use CONTROL + F to search for whatever array or name you're looking for, in the format of [CATEGORY] SECTION.

//categoryColors is a parallel Array for the 17 categories stored in the "categories" array, where the index of a category correspondes to its Tag's color.
export const categories = ["MILITARY", "NAVY", "FLAGSHIPS", "DIPLOMACY", "ECONOMY", "TECHNOLOGY", "COURT", "GOVERNMENT", "ESTATES", "HRE", "CULTURE", "STABILITY", "SUBJECT", "ESPIONAGE", "RELIGION", "COLONIZATION", "TRADE"]
export const categoryColors = ["#c40c0c", "#000080", "#3b3bbf", "#c7c7eb", "#04bd29", "#5c5e5c", "#a0522d", "#e67f2c", "#ebb634", "#8736cf", "#87aded", "#91d7ff", "#310b85", "#edda5c", "#449e5c", "#46dbb6", "rgb(1 100 222)"]

// function compare( a, b ) {
//     if ( a.name < b.name ){
//         return -1;
//     }
//     if ( a.name > b.name ){
//         return 1;
//     }
//     return 0;
// }
//This is a sort function, may or may not use.

export const modifiers = [
    {
        name: "Army Tradition",
        desc: "Adds to the rate of army tradition gained each year.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Army Tradition Decay",
        desc: "Adds to the decay rate of army tradition.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Army Tradition From Battle",
        desc: "Modifies the army tradition bonus when gained through battles.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Yearly Army Professionalism",
        desc: "Modifies the rate of army professionalism gained each year.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Drill Gain Modifier",
        desc: "Modifies the army drill gains while drilling",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Drill Decay Modifier",
        desc: "Modifies the army drill decay rate per year.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Infantry Cost",
        desc: "Modifies the base cost of infantry units.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Infantry Power",
        desc: "Modifies the power infantry gain from unit pips.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Infantry Fire",
        desc: "Adds to the base fire pips for infantry.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Infantry Shock",
        desc: "Adds to the base shock pips for infantry.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Cavalry Cost",
        desc: "Modifies the base cost of cavalry units.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Cavalry Power",
        desc: "Modifies the power cavalry gain from unit pips.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Cavalry Fire",
        desc: "Adds to the base fire pips for cavalry.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Cavalry Shock",
        desc: "Adds to the base shock pips for cavalry.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Artillery Cost",
        desc: "Modifies the base cost of artillery units.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Artillery Power",
        desc: "Modifies the power artillery gain from unit pips.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Artillery Fire",
        desc: "Adds to the base fire pips for artillery.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Artillery Shock",
        desc: "Adds to the base shock pips for artillery.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Cav To Inf Ratio",
        desc: "Adds to the ratio required to negate the insufficient support penalty.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Cavalry Flanking",
        desc: "Modifies the effectiveness of cavalry flanking.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Artillery Bonus Vs Fort",
        desc: "Adds to the bonus artillery get versus forts.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Backrow Artillery Damage",
        desc: "Modifies the bonus damage artillery inflict when in the backrow during combat.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Discipline",
        desc: "Modifies the discipline of land units.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Mercenary Discipline",
        desc: "Modifies the discipline of mercenary units.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Land Morale",
        desc: "Modifies the land morale of land units.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Defensiveness",
        desc: "Modifies the siege defensiveness that affects siege phase length.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Siege Ability",
        desc: "Modifies the siege ability that affects siege phase length. Reverse concept of defensiveness.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Movement Speed",
        desc: "Modifies the base movement speed for all land units.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Fire Damage",
        desc: "Modifies the fire damage done by land units.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Fire Damage Received",
        desc: "Modifies the fire damage taken by land units.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Shock Damage",
        desc: "Modifies the shock damage done by land units.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Shock Damage Received",
        desc: "Modifies the shock damage taken by land units.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Recover Army Morale Speed",
        desc: "Modifies the army morale recovery speed.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Siege Blockade Progress",
        desc: "Modifies the bonus siege status by blockaded.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Reserves Organisation",
        desc: "Modifies the morale damage taken by units in reserves (i.e. not in battle, but engaged with another unit)",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Land Attrition",
        desc: "Modifies the attrition taken by land units.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Reinforce Cost Modifier",
        desc: "Modifies the cost of reinforcements when units are reinforced.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Reinforce Speed",
        desc: "Modifies the rate at which units are reinforced with new men.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Manpower Recovery Speed",
        desc: "Modifies the rate at which manpower is recovered.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Global Manpower",
        desc: "Adds to the country's total manpower pool. 1 equals 1000 men.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Global Manpower Modifier",
        desc: "Modifies a country's total manpower pool.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Global Regiment Cost",
        desc: "Modifies the base unit cost for all land units.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Global Regiment Recruit Speed",
        desc: "Modifies the base speed at which land units are recruited.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Global Supply Limit Modifier",
        desc: "Modifies the supply limit of provinces",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Land Forcelimit",
        desc: "Adds to a country's force limit.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Land Forcelimit Modifier",
        desc: "Modifies a country's force limit.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Land Maintenance Modifier",
        desc: "Modifies the maintenance cost of all land units.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Mercenary Cost",
        desc: "Modifies the base cost for mercenary units.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Merc Maintenance Modifier",
        desc: "Modifies the maintenance cost of all mercenary units.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Possible Condottieri",
        desc: "Modifies the base condottieri limit.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Hostile Attrition",
        desc: "Adds to the attrition enemies take in a country's provinces.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Garrison Size",
        desc: "Modifies the base garrison size in provinces.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Global Garrison Growth",
        desc: "Modifies the base garrison growth in provinces.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Fort Maintenance Modifier",
        desc: "Modifies the base fort maintenance cost.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Rival Border Fort Maintenance",
        desc: "Modifies the base fort maintenance cost for forts in provinces that border rivals.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "War Exhaustion",
        desc: "Adds to the monthly war exhaustion rate.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "War Exhaustion Cost",
        desc: "Modifies the diplomatic power cost for reducing war exhaustion.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Leader Land Fire",
        desc: "Adds to the minimum fire pip count a leader can be generated with.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Leader Land Manuever",
        desc: "Adds to the minimum maneuver pip count a leader can be generated with.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Leader Land Shock",
        desc: "Adds to the minimum shock pip count a leader can be generated with.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Leader Siege",
        desc: "Adds to the minimum siege pip count a leader can be generated with.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "General Cost",
        desc: "Modifies the base military power cost for recruiting Generals.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Free Leader Pool",
        desc: "Adds to the maximum amount of free leaders.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Raze Power Gain",
        desc: "Modifies the amount of monarch power gained from razing.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Loot Amount",
        desc: "Modifies the amount of loot taken at once during looting.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Available Province Loot",
        desc: "Modifies the amount of loot available in a province.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Prestige From Land",
        desc: "Modifies the prestige bonus from combat.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Amount Of Banners",
        desc: "Modifies the maximum amount of banners available.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "War Taxes Cost Modifier",
        desc: "Modifies the military power cost for raising war taxes.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Leader Cost",
        desc: "Modifies the military power cost for hiring leaders.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "May Recruit Female Generals",
        desc: "Allows the recruitment of female generals.",
        function: "CONSTANT - TOGGLE",
        type: "PERCENTAGE",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Special Unit Forcelimit",
        desc: "Modifies the allowed forcelimit of special units such as Rajput regiments, etc.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Manpower In True Faith Province",
        desc: "Modifies the amount of manpower gained from provinces that follow the true faith of a country.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    {
        name: "Mercenary Manpower",
        desc: "Modifies the amount of manpower mercenary companies have.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "MILITARY",
        image: "/images/icons/landLeaderFire.png",
    },
    //NAVY SECTION
    {
        name: "Navy Tradition",
        desc: "Adds to the yearly navy tradition rate.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "NAVY",
        image: "/images/icons/heavy_ship_cost.png",
    },
    {
        name: "Navy Tradition Decay",
        desc: "Adds to the decay rate of navy tradition.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "NAVY",
        image: "/images/icons/heavy_ship_cost.png",
    },
    {
        name: "Naval Tradition From Battle",
        desc: "Modifies the base navy tradition gained from battles.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "NAVY",
        image: "/images/icons/heavy_ship_cost.png",
    },
    {
        name: "Naval Tradition From Trade",
        desc: "Modifies the base navy tradition gained from protecting trade.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "NAVY",
        image: "/images/icons/heavy_ship_cost.png",
    },
    {
        name: "Heavy Ship Cost",
        desc: "Modifies the base cost of heavy ships.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "NAVY",
        image: "/images/icons/heavy_ship_cost.png",
    },
    {
        name: "Heavy Ship Power",
        desc: "Modifies the power heavy ships gain from unit pips.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "NAVY",
        image: "/images/icons/heavy_ship_cost.png",
    },
    {
        name: "Light Ship Cost",
        desc: "Modifies the base cost of light ships.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "NAVY",
        image: "/images/icons/heavy_ship_cost.png",
    },
    {
        name: "Light Ship Power",
        desc: "Modifies the power light ships gain from unit pips.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "NAVY",
        image: "/images/icons/heavy_ship_cost.png",
    },
    {
        name: "Galley Cost",
        desc: "Modifies the base cost of galley ships.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "NAVY",
        image: "/images/icons/heavy_ship_cost.png",
    },
    {
        name: "Galley Power",
        desc: "Modifies the power galley ships gain from unit pips.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "NAVY",
        image: "/images/icons/heavy_ship_cost.png",
    },
    {
        name: "Transport Cost",
        desc: "Modifies the base cost of transport ships.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "NAVY",
        image: "/images/icons/heavy_ship_cost.png",
    },
    {
        name: "Transport Power",
        desc: "Modifies the power transport ships gain from unit pips.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "NAVY",
        image: "/images/icons/heavy_ship_cost.png",
    },
    {
        name: "Global Ship Cost",
        desc: "Modifies the base cost of all ships.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "NAVY",
        image: "/images/icons/heavy_ship_cost.png",
    },
    {
        name: "Global Ship Recruit Speed",
        desc: "Modifies the base recruitmend speed of all ships.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "NAVY",
        image: "/images/icons/heavy_ship_cost.png",
    },
    {
        name: "Global Ship Repair",
        desc: "Modifies the base repair speed (in port) of all ships.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "NAVY",
        image: "/images/icons/heavy_ship_cost.png",
    },
    {
        name: "Naval Forcelimit",
        desc: "Adds to a country's naval force limit.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "NAVY",
        image: "/images/icons/heavy_ship_cost.png",
    },
    {
        name: "Naval Forcelimit Modifier",
        desc: "Modifies a country's naval force limit.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "NAVY",
        image: "/images/icons/heavy_ship_cost.png",
    },
    {
        name: "Naval Maintenance Modifier",
        desc: "Modifies the naval maintenance for all ships.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "NAVY",
        image: "/images/icons/heavy_ship_cost.png",
    },
    {
        name: "Global Sailors",
        desc: "Adds to a country's maximum sailor pool.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "NAVY",
        image: "/images/icons/heavy_ship_cost.png",
    },
    {
        name: "Global Sailors Modifier",
        desc: "Modifies a country's maximum sailor pool.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "NAVY",
        image: "/images/icons/heavy_ship_cost.png",
    },
    {
        name: "Sailor Maintenance Modifer",
        desc: "Modifies the sailor maintenance for all ships.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "NAVY",
        image: "/images/icons/heavy_ship_cost.png",
    },
    {
        name: "Sailors Recovery Speed",
        desc: "Modifies the sailor recovery rate for all ships.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "NAVY",
        image: "/images/icons/heavy_ship_cost.png",
    },
    {
        name: "Blockade Efficiency",
        desc: "Modifies the efficiency of blockades against enemies.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "NAVY",
        image: "/images/icons/heavy_ship_cost.png",
    },
    {
        name: "Capture Ship Chance",
        desc: "Adds to the chance for ship capture during naval battles.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "NAVY",
        image: "/images/icons/heavy_ship_cost.png",
    },
    {
        name: "Global Naval Engagement Modifier",
        desc: "Modifies the maximum naval engagement width.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "NAVY",
        image: "/images/icons/heavy_ship_cost.png",
    },
    {
        name: "Naval Attrition",
        desc: "Modifies the naval attrition taken by ships.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "NAVY",
        image: "/images/icons/heavy_ship_cost.png",
    },
    {
        name: "Naval Morale",
        desc: "Modifies the naval morale of all ships.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "NAVY",
        image: "/images/icons/heavy_ship_cost.png",
    },
    {
        name: "Ship Durability",
        desc: "Modifies the durability of all ships. (discipline for ships)",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "NAVY",
        image: "/images/icons/heavy_ship_cost.png",
    },
    {
        name: "Sunk Ship Morale Hit Recieved",
        desc: "Modifies the morale damage taken during battle by losing ships.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "NAVY",
        image: "/images/icons/heavy_ship_cost.png",
    },
    {
        name: "Recover Navy Morale Speed",
        desc: "Modifies the morale recovery rate of ships.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "NAVY",
        image: "/images/icons/heavy_ship_cost.png",
    },
    {
        name: "Prestige From Naval",
        desc: "Modifies the prestige gained through naval battles.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "NAVY",
        image: "/images/icons/heavy_ship_cost.png",
    },
    {
        name: "Leader Naval Fire",
        desc: "Adds to the minimum fire pip count a leader can be generated with.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "NAVY",
        image: "/images/icons/heavy_ship_cost.png",
    },
    {
        name: "Leader Naval Manuever",
        desc: "Adds to the minimum maneuver pip count a leader can be generated with.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "NAVY",
        image: "/images/icons/heavy_ship_cost.png",
    },
    {
        name: "Leader Naval Shock",
        desc: "Adds to the minimum shock pip count a leader can be generated with.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "NAVY",
        image: "/images/icons/heavy_ship_cost.png",
    },
    {
        name: "Own Coast Naval Combat Bonus",
        desc: "Modifies the combat bonus navies gain when sailing in coastal tiles that border their home nation.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "NAVY",
        image: "/images/icons/heavy_ship_cost.png",
    },
    {
        name: "Admiral Cost",
        desc: "Modifies the cost of hiring an admiral.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "NAVY",
        image: "/images/icons/heavy_ship_cost.png",
    },
    {
        name: "Movement Speed Onto Off Boat Modifier",
        desc: "Modifies the speed at which troops disembark off ships into provinces.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "NAVY",
        image: "/images/icons/heavy_ship_cost.png",
    },
    {
        name: "Global Naval Barrage Cost",
        desc: "Modifies the cost for using the ‘Naval Barrage’ action.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "NAVY",
        image: "/images/icons/heavy_ship_cost.png",
    },
    {
        name: "Allowed Marine Fraction",
        desc: "Modifies the amount of marines allowed to be recruited.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "NAVY",
        image: "/images/icons/heavy_ship_cost.png",
    },
    {
        name: "Flagship Cost",
        desc: "Modifies the cost of building a flagship.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "NAVY",
        image: "/images/icons/heavy_ship_cost.png",
    },
    {
        name: "May Perform Slave Raid",
        desc: "Allows ships to perform slave raids.",
        function: "CONSTANT - TOGGLE",
        type: "PERCENTAGE",
        category: "NAVY",
        image: "/images/icons/heavy_ship_cost.png",
    },
    {
        name: "May Perform Slave Raid On Same Religion",
        desc: "Grants the abiliy to conduct slave raids against nations that share the same religion.",
        function: "CONSTANT - TOGGLE",
        type: "PERCENTAGE",
        category: "NAVY",
        image: "/images/icons/heavy_ship_cost.png",
    },
    //FLAGSHIP SECTION
    {
        name: "Admiral Skill Gain Modifier",
        desc: "The monthly chance that an admiral gains a pip while he is assigned to a fleet that is on a mission and contains a flagship with this modifier",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "FLAGSHIPS",
        image: "/images/icons/spanish_grand_armada.png",
    },
    {
        name: "Flagship Durability",
        desc: "Modifies the ship durability for the flagship.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "FLAGSHIPS",
        image: "/images/icons/spanish_grand_armada.png",
    },
    {
        name: "Flagship Morale",
        desc: "Modifies the naval morale for the flagship.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "FLAGSHIPS",
        image: "/images/icons/spanish_grand_armada.png",
    },
    {
        name: "Flagship Naval Engagement Modifier",
        desc: "Modifies the global naval engagement size for the flagship.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "FLAGSHIPS",
        image: "/images/icons/spanish_grand_armada.png",
    },
    {
        name: "Flagship Landing Penalty",
        desc: "Modifies the disembarkment penalty for the flagship.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "FLAGSHIPS",
        image: "/images/icons/spanish_grand_armada.png",
    },
    {
        name: "Number Of Cannons Flagship Modifier",
        desc: "Modifies the number of cannons for the flagship.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "FLAGSHIPS",
        image: "/images/icons/spanish_grand_armada.png",
    },
    {
        name: "Naval Maintenance Flagship Modifier",
        desc: "Modifies the naval maintenance for the flagship.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "FLAGSHIPS",
        image: "/images/icons/spanish_grand_armada.png",
    },
    {
        name: "Trade Power In Fleet Modifier",
        desc: "Modifies the trade power conferred by the flagship and all other ships within its fleet.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "FLAGSHIPS",
        image: "/images/icons/spanish_grand_armada.png",
    },
    {
        name: "Morale In Fleet Modifier",
        desc: "Modifies the naval morale for the flagship and all other ships within its fleet.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "FLAGSHIPS",
        image: "/images/icons/spanish_grand_armada.png",
    },
    {
        name: "Blockade Impact On Siege In Fleet Modifier",
        desc: "Modifies the blockade impact of the flagship and all other ships within its fleet.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "FLAGSHIPS",
        image: "/images/icons/spanish_grand_armada.png",
    },
    {
        name: "Exploration Mission Range In Fleet Modifier",
        desc: "Modifies the exploration mission range for the flagship and all other ships within its fleet.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "FLAGSHIPS",
        image: "/images/icons/spanish_grand_armada.png",
    },
    {
        name: "Barrage Cost In Fleet Modifier",
        desc: "Modifies the ‘Naval Barrage’ action cost for the flagship and all other ships within its fleet.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "FLAGSHIPS",
        image: "/images/icons/spanish_grand_armada.png",
    },
    {
        name: "Naval Attrition In Fleet Modifier",
        desc: "Modifies the naval attrition suffered by the flagship and all other ships within its fleet.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "FLAGSHIPS",
        image: "/images/icons/spanish_grand_armada.png",
    },
    {
        name: "Privateering Efficiency In Fleet Modifier",
        desc: "Modifies the privateering efficiency of the flagship and all other ships within its fleet.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "FLAGSHIPS",
        image: "/images/icons/spanish_grand_armada.png",
    },
    {
        name: "Prestige From Battles In Fleet Modifier",
        desc: "Modifies the amount of prestige gained from battles for the flagship and all other ships within its fleet.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "FLAGSHIPS",
        image: "/images/icons/spanish_grand_armada.png",
    },
    {
        name: "Naval Tradition In Fleet Modifier",
        desc: "Modifies the amount of Naval Tradition gained from battles for the flagship and all other ships within its fleet.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "FLAGSHIPS",
        image: "/images/icons/spanish_grand_armada.png",
    },
    {
        name: "Cannons For Hunting Pirates In Fleet",
        desc: "Modifies the amount of cannons for the flagship and all other ships within its fleet whilst on the Hunting Pirates mission.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "FLAGSHIPS",
        image: "/images/icons/spanish_grand_armada.png",
    },
    {
        name: "Movement Speed In Fleet Modifier",
        desc: "Modifies the movement speed for the flagship and all other ships within its fleet.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "FLAGSHIPS",
        image: "/images/icons/spanish_grand_armada.png",
    },
    //DIPLOMATIC SECTION
    {
        name: "Diplomats",
        desc: "Adds to a country's diplomat count.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "DIPLOMACY",
        image: "/images/icons/diplomatic_relations.png",
    },
    {
        name: "Diplomatic Reputation",
        desc: "Adds to a country's diplomatic reputation.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "DIPLOMACY",
        image: "/images/icons/diplomatic_relations.png",
    },
    {
        name: "Diplomatic Upkeep",
        desc: "Adds to the maximum number of free diplomatic relations.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "DIPLOMACY",
        image: "/images/icons/diplomatic_relations.png",
    },
    {
        name: "Envoy Travel Time",
        desc: "Modifies diplomat travel time during actions.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "DIPLOMACY",
        image: "/images/icons/diplomatic_relations.png",
    },
    {
        name: "Fabricate Claims Cos",
        desc: "Modifies spy network cost for fabricating claim.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "DIPLOMACY",
        image: "/images/icons/diplomatic_relations.png",
    },
    {
        name: "Improve Relation Modifier",
        desc: "Modifies the speed of the ‘Improve Relations’ diplomatic action.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "DIPLOMACY",
        image: "/images/icons/diplomatic_relations.png",
    },
    {
        name: "Vassal Forcelimit Bonus",
        desc: "Modifies the bonus to a country's forcelimit from their subjects.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "DIPLOMACY",
        image: "/images/icons/diplomatic_relations.png",
    },
    {
        name: "Vassal Income",
        desc: "Modifies the bonus to a country's income from their subjects.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "DIPLOMACY",
        image: "/images/icons/diplomatic_relations.png",
    },
    {
        name: "Aggresive Expansion Impact",
        desc: "Modifies the total size of aggressive expansion gained during actions that confer it.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "DIPLOMACY",
        image: "/images/icons/diplomatic_relations.png",
    },
    {
        name: "Claim Duration",
        desc: "Modifies the duration of claims. (not uses in vanilla)",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "DIPLOMACY",
        image: "/images/icons/diplomatic_relations.png",
    },
    {
        name: "Diplomatic Annexation Cost",
        desc: "Modifies the diplomatic power cost for annexation.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "DIPLOMACY",
        image: "/images/icons/diplomatic_relations.png",
    },
    {
        name: "Province Warscore Cost",
        desc: "Modifies the warscore cost for taking provinces.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "DIPLOMACY",
        image: "/images/icons/diplomatic_relations.png",
    },
    {
        name: "Unjustified Demands",
        desc: "Modifies the weighting of demands in peace treaties.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "DIPLOMACY",
        image: "/images/icons/diplomatic_relations.png",
    },
    {
        name: "Enemy Core Creation",
        desc: "Modifies the cost of coring provinces for enemies that have your cores.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "DIPLOMACY",
        image: "/images/icons/diplomatic_relations.png",
    },
    {
        name: "Rival Change Cost",
        desc: "Modifies the diplomatic power cost to change rivals.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "DIPLOMACY",
        image: "/images/icons/diplomatic_relations.png",
    },
    {
        name: "Justify Trade Conflict Cost",
        desc: "Modifies the spy network cost to justify trade conflicts.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "DIPLOMACY",
        image: "/images/icons/diplomatic_relations.png",
    },
    {
        name: "Stability Cost To Declare War",
        desc: "Modifies the stability cost to declare war. Default is 0 with a casus belli and no truce.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "DIPLOMACY",
        image: "/images/icons/diplomatic_relations.png",
    },
    //ECONOMY SECTION
    {
        name: "Global Tax Income",
        desc: "Adds to the base tax income per year (i.e. 12 equals 1 extra per month).",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "ECONOMY",
        image: "/images/icons/overseas_income.png",
    },
    {
        name: "Global Tax Modifier",
        desc: "Modifies the base tax income by a percentage.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "ECONOMY",
        image: "/images/icons/overseas_income.png",
    },
    {
        name: "Production Efficiency",
        desc: "Modifies the base production income by a percentage.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "ECONOMY",
        image: "/images/icons/overseas_income.png",
    },
    {
        name: "State Maintenance Modifier",
        desc: "Modifies the maintenance cost for states.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "ECONOMY",
        image: "/images/icons/overseas_income.png",
    },
    {
        name: "Inflation Action Cost",
        desc: "Modifies the administrative power cost for reducing inflation.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "ECONOMY",
        image: "/images/icons/overseas_income.png",
    },
    {
        name: "Inflation Reduction",
        desc: "Adds to the base yearly inflation reduction rate.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "ECONOMY",
        image: "/images/icons/overseas_income.png",
    },
    {
        name: "Interest",
        desc: "Adds to the base interest rate.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "ECONOMY",
        image: "/images/icons/overseas_income.png",
    },
    {
        name: "Development Cost",
        desc: "Modifies the development cost for provinces.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "ECONOMY",
        image: "/images/icons/overseas_income.png",
    },
    {
        name: "Build Cost",
        desc: "Modifies all building costs.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "ECONOMY",
        image: "/images/icons/overseas_income.png",
    },
    {
        name: "Build Time",
        desc: "Modifies all building construction times.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "ECONOMY",
        image: "/images/icons/overseas_income.png",
    },
    {
        name: "Administrative Efficiency",
        desc: "Modifies the base core creation cost, diplo-annexation costs and the impact of province development on overextension and warscore cost.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "ECONOMY",
        image: "/images/icons/overseas_income.png",
    },
    {
        name: "Core Creation",
        desc: "Modifies the base core creation cost.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "ECONOMY",
        image: "/images/icons/overseas_income.png",
    },
    {
        name: "Core Decay On Your Own",
        desc: "Modifies the rate at which the cores of a country will decay when under the ownership of a different country.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "ECONOMY",
        image: "/images/icons/overseas_income.png",
    },
    //TECHNOLOGY
    {
        name: "Admin Tech Cost Modifier",
        desc: "Modifies the monarch power cost of administrative technologies.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "TECHNOLOGY",
        image: "/images/icons/tech_cost.png",
    },
    {
        name: "Diplomatic Tech Cost Modifier",
        desc: "Modifies the monarch power cost of diplomatic technologies.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "TECHNOLOGY",
        image: "/images/icons/tech_cost.png",
    },
    {
        name: "Military Tech Cost Modifier",
        desc: "Modifies the monarch power cost of military technologies.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "TECHNOLOGY",
        image: "/images/icons/tech_cost.png",
    },
    {
        name: "Technology Cost",
        desc: "Modifies the monarch power  cost of all technologies.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "TECHNOLOGY",
        image: "/images/icons/tech_cost.png",
    },
    {
        name: "Idea Cost",
        desc: "Modifies the monarch power cost of purchasable ideas.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "TECHNOLOGY",
        image: "/images/icons/tech_cost.png",
    },
    {
        name: "Embracement Cost",
        desc: "Modifies the ducat cost for embracing an institution.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "TECHNOLOGY",
        image: "/images/icons/tech_cost.png",
    },
    {
        name: "Global Institution Spread",
        desc: "Modifies the rate of spread for institutions in all owned provinces.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "TECHNOLOGY",
        image: "/images/icons/tech_cost.png",
    },
    {
        name: "Institution Spread From True Faith",
        desc: "Modifies the rate of spread for institutions in owned provinces following the owner's religion.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "TECHNOLOGY",
        image: "/images/icons/tech_cost.png",
    },
    {
        name: "Native Advancement Cost",
        desc: "Modifies the monarch power cost of native advancements.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "TECHNOLOGY",
        image: "/images/icons/tech_cost.png",
    },
    {
        name: "All Power Cost",
        desc: "Modifies the monarch power cost of '''every''' action that costs monarch power.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "TECHNOLOGY",
        image: "/images/icons/tech_cost.png",
    },
    {
        name: "Innovativeness Gain",
        desc: "Modifies the amount of innovativeness gained",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "TECHNOLOGY",
        image: "/images/icons/tech_cost.png",
    },
    {
        name: "Free Administrative Policy",
        desc: "Modifies the amount of free administrative policies.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "TECHNOLOGY",
        image: "/images/icons/tech_cost.png",
    },
    {
        name: "Free Diplomatic Policy",
        desc: "Modifies the amount of free diplomatic policies.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "TECHNOLOGY",
        image: "/images/icons/tech_cost.png",
    },
    {
        name: "Free Military Policy",
        desc: "Modifies the amount of free military policies.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "TECHNOLOGY",
        image: "/images/icons/tech_cost.png",
    },
    {
        name: "Possible Administrative Policy",
        desc: "Modifies the amount of administrative policy slots.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "TECHNOLOGY",
        image: "/images/icons/tech_cost.png",
    },
    {
        name: "Possible Diplomatic Policy",
        desc: "Modifies the amount of diplomatic policy slots.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "TECHNOLOGY",
        image: "/images/icons/tech_cost.png",
    },
    {
        name: "Possible Military Policy",
        desc: "Modifies the amount of military policy slots.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "TECHNOLOGY",
        image: "/images/icons/tech_cost.png",
    },
    {
        name: "Possible Policy",
        desc: "Modifies the amount of all policy slots.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "TECHNOLOGY",
        image: "/images/icons/tech_cost.png",
    },
    {
        name: "Free Policy",
        desc: "Modifies the amount of policy slots.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "TECHNOLOGY",
        image: "/images/icons/tech_cost.png",
    },
    {
        name: "Country Admin Power",
        desc: "Modifies the monthly administrative power a country generates.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "TECHNOLOGY",
        image: "/images/icons/tech_cost.png",
    },
    {
        name: "Country Diplomatic Power",
        desc: "Modifies the monthly diplomatic power a country generates.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "TECHNOLOGY",
        image: "/images/icons/tech_cost.png",
    },
    {
        name: "Country Military Power",
        desc: "Modifies the monthly military power a country generates.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "TECHNOLOGY",
        image: "/images/icons/tech_cost.png",
    },
    //COURT SECTION
    {
        name: "Prestige",
        desc: "Adds to the base yearly rate of prestige.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "COURT",
        image: "/images/icons/yearly_prestige.png",
    },
    {
        name: "Prestige Decay",
        desc: "Adds to the base rate of prestige decay.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "COURT",
        image: "/images/icons/yearly_prestige.png",
    },
    {
        name: "Monthly Splendor",
        desc: "Adds to the monthly rate of splendor points.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "COURT",
        image: "/images/icons/yearly_prestige.png",
    },
    {
        name: "Yearly Corruption",
        desc: "Adds to the yearly rate of corruption.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "COURT",
        image: "/images/icons/yearly_prestige.png",
    },
    {
        name: "Advisor Cost",
        desc: "Modifies the base cost of advisors.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "COURT",
        image: "/images/icons/yearly_prestige.png",
    },
    {
        name: "Advisor Pool",
        desc: "Adds to the pool size for advisors.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "COURT",
        image: "/images/icons/yearly_prestige.png",
    },
    {
        name: "Female Advisor Chance",
        desc: "Modifies the base chance rate for female advisors.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "COURT",
        image: "/images/icons/yearly_prestige.png",
    },
    {
        name: "Heir Chance",
        desc: "Modifies the base chance for an heir during the heir generation tick.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "COURT",
        image: "/images/icons/yearly_prestige.png",
    },
    {
        name: "Monarch Admin Power",
        desc: "Adds to the base ADM skill a ruler, heir and consort can be generated with.<br>",
        function: "OES NOT AFFECT RULERS CREATED WITH <CODE>FIXED = YES</CODE>.",
        type: "PERCENTAGE",
        category: "COURT",
        image: "/images/icons/yearly_prestige.png",
    },
    {
        name: "Monarch Diplomatic Power",
        desc: "Adds to the base DIP skill a ruler, heir and consort can be generated with.<br>",
        function: "OES NOT AFFECT RULERS CREATED WITH <CODE>FIXED = YES</CODE>.",
        type: "PERCENTAGE",
        category: "COURT",
        image: "/images/icons/yearly_prestige.png",
    },
    {
        name: "Monarch Military Power",
        desc: "Adds to the base MIL skill a ruler, heir and consort can be generated with.<br>",
        function: "OES NOT AFFECT RULERS CREATED WITH <CODE>FIXED = YES</CODE>.",
        type: "PERCENTAGE",
        category: "COURT",
        image: "/images/icons/yearly_prestige.png",
    },
    {
        name: "Admin Advisor Cost",
        desc: "Modifies the cost of hiring an administrative advisor.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "COURT",
        image: "/images/icons/yearly_prestige.png",
    },
    {
        name: "Dip Advisor Cost",
        desc: "Modifies the cost of hiring an diplomatic advisor.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "COURT",
        image: "/images/icons/yearly_prestige.png",
    },
    {
        name: "Mil Advisor Cost",
        desc: "Modifies the cost of hiring an military advisor.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "COURT",
        image: "/images/icons/yearly_prestige.png",
    },
    {
        name: "Monthly Support Heir Gain",
        desc: "Modifies the monthly gain in support for the heir of a country in an country that uses the ‘Elective Monarchy’ mechanics.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "COURT",
        image: "/images/icons/yearly_prestige.png",
    },
    {
        name: "Power Projection From Insults",
        desc: "Modifies the amount of power projection gained when using the ‘Insult’ diplomatic action.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "COURT",
        image: "/images/icons/yearly_prestige.png",
    },
    //GOVERNMENT SECTION
    {
        name: "Yearly Absolutism",
        desc: "Adds to the yearly base rate of absolutism.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "GOVERNMENT",
        image: "/images/icons/yearly_legitimacy.png",
    },
    {
        name: "Max Absolutism",
        desc: "Adds to the maximum value of absolutism. Internally absolutism bonuses do not scale above 100.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "GOVERNMENT",
        image: "/images/icons/yearly_legitimacy.png",
    },
    {
        name: "Legitimacy",
        desc: "Adds to the yearly rate of legitimacy.<br>Does not appear or have an effect if a country's government does not use legitimacy.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "GOVERNMENT",
        image: "/images/icons/yearly_legitimacy.png",
    },
    {
        name: "Republican Tradition",
        desc: "Adds to the yearly rate of republican tradition.<br>Does not appear or have an effect if a country's government does not use republican tradition.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "GOVERNMENT",
        image: "/images/icons/yearly_legitimacy.png",
    },
    {
        name: "Devotion",
        desc: "Adds to the yearly rate of devotion.<br>Does not appear or have an effect if a country's government does not use devotion.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "GOVERNMENT",
        image: "/images/icons/yearly_legitimacy.png",
    },
    {
        name: "Horde Unity",
        desc: "Adds to the yearly rate of horde unity.<br>Does not appear or have an effect if a country's government does not use horde unity.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "GOVERNMENT",
        image: "/images/icons/yearly_legitimacy.png",
    },
    {
        name: "Meritocracy",
        desc: "Adds to the yearly rate of meritocracy. Does not appear or have an effect if a country's government does not use meritocracy.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "GOVERNMENT",
        image: "/images/icons/yearly_legitimacy.png",
    },
    {
        name: "Monthly Militarized Society",
        desc: "Adds to the monthly rate of militarisation for governments with the militarisation mechanic.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "GOVERNMENT",
        image: "/images/icons/yearly_legitimacy.png",
    },
    {
        name: "Yearly Tribal Allegiance",
        desc: "Adds to the yearly rate of tribal allegiance for governments with the tribal allegiance mechanic.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "GOVERNMENT",
        image: "/images/icons/yearly_legitimacy.png",
    },
    {
        name: "<Faction> Influence",
        desc: "Adds to the monthly rate of faction influence. <br>Generated automatically for all factions in {{path|common/factions}}.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "GOVERNMENT",
        image: "/images/icons/yearly_legitimacy.png",
    },
    {
        name: "Imperial Mandate",
        desc: "Adds to the rate of Mandate gained per month.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "GOVERNMENT",
        image: "/images/icons/yearly_legitimacy.png",
    },
    {
        name: "Election Cycle",
        desc: "Adds to the duration of an election cycle for the current nation. Negative values shorten the duration, positive values add to it.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "GOVERNMENT",
        image: "/images/icons/yearly_legitimacy.png",
    },
    {
        name: "Candidate Random Bonus",
        desc: "Adds to the randomized stats a republican candidate may receive during elections.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "GOVERNMENT",
        image: "/images/icons/yearly_legitimacy.png",
    },
    {
        name: "Reelection Cost",
        desc: "Modifies the cost in Republican Tradition when re-electing candidates.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "GOVERNMENT",
        image: "/images/icons/yearly_legitimacy.png",
    },
    {
        name: "Reform Progress Growth",
        desc: "Adds to the rate of government reform progress gain.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "GOVERNMENT",
        image: "/images/icons/yearly_legitimacy.png",
    },
    {
        name: "Governing Capacity",
        desc: "Adds to the base governing capacity.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "GOVERNMENT",
        image: "/images/icons/yearly_legitimacy.png",
    },
    {
        name: "Governing Capacity Modifier",
        desc: "Modifies the base governing capacity.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "GOVERNMENT",
        image: "/images/icons/yearly_legitimacy.png",
    },
    {
        name: "State Governing Cost",
        desc: "Modifies the governing capacity usage of states.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "GOVERNMENT",
        image: "/images/icons/yearly_legitimacy.png",
    },
    {
        name: "Trade Company Governing Cost",
        desc: "Modifies the governing capacity usage of trade companies.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "GOVERNMENT",
        image: "/images/icons/yearly_legitimacy.png",
    },
    {
        name: "Expand Administration Cost",
        desc: "Modifies the cost of the ‘Expand Administration’ action.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "GOVERNMENT",
        image: "/images/icons/yearly_legitimacy.png",
    },
    {
        name: "Yearly Revolutionary Zeal",
        desc: "Adds to the yearly base rate of revolutionary zeal.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "GOVERNMENT",
        image: "/images/icons/yearly_legitimacy.png",
    },
    {
        name: "Max Revolutionary Zeal",
        desc: "Adds to the maximum value of revolutionary zeal. Internally revolutionary zeal bonuses do not scale above 100.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "GOVERNMENT",
        image: "/images/icons/yearly_legitimacy.png",
    },
    //ESTATES SECTION
    {
        name: "Burghers Influence Modifier",
        desc: "Modifies to the influence of the Burghers estate.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "ESTATES",
        image: "/images/icons/estates.png",
    },
    {
        name: "Burghers Loyalty Modifier",
        desc: "Modifies to the loyalty equilibrium of the Burghers estate.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "ESTATES",
        image: "/images/icons/estates.png",
    },
    {
        name: "Clergy Influence Modifier",
        desc: "Modifies to the influence of the Clergy estate.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "ESTATES",
        image: "/images/icons/estates.png",
    },
    {
        name: "Clergy Loyalty Modifier",
        desc: "Modifies to the loyalty equilibrium of the Clergy estate.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "ESTATES",
        image: "/images/icons/estates.png",
    },
    {
        name: "Nobility Influence Modifier",
        desc: "Modifies to the influence of the Nobility estate.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "ESTATES",
        image: "/images/icons/estates.png",
    },
    {
        name: "Nobility Loyalty Modifier",
        desc: "Modifies to the loyalty equilibrium of the Nobility estate.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "ESTATES",
        image: "/images/icons/estates.png",
    },
    {
        name: "Cossacks Influence Modifier",
        desc: "Modifies to the influence of the Cossacks estate.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "ESTATES",
        image: "/images/icons/estates.png",
    },
    {
        name: "Cossacks Loyalty Modifier",
        desc: "Modifies to the loyalty equilibrium of the Cossacks estate.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "ESTATES",
        image: "/images/icons/estates.png",
    },
    {
        name: "Dhimmi Influence Modifier",
        desc: "Modifies to the influence of the Dhimmi estate.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "ESTATES",
        image: "/images/icons/estates.png",
    },
    {
        name: "Dhimmi Loyalty Modifier",
        desc: "Modifies to the loyalty equilibrium of the Dhimmi estate.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "ESTATES",
        image: "/images/icons/estates.png",
    },
    {
        name: "Tribes Influence Modifier",
        desc: "Modifies to the influence of the Tribes estate.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "ESTATES",
        image: "/images/icons/estates.png",
    },
    {
        name: "Tribes Loyalty Modifier",
        desc: "Modifies to the loyalty equilibrium of the Tribes estate.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "ESTATES",
        image: "/images/icons/estates.png",
    },
    {
        name: "Brahmins Influence Modifier",
        desc: "Modifies to the influence of the Brahmins estate.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "ESTATES",
        image: "/images/icons/estates.png",
    },
    {
        name: "Brahmins Loyalty Modifier",
        desc: "Modifies to the loyalty equilibrium of the Brahmins estate.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "ESTATES",
        image: "/images/icons/estates.png",
    },
    {
        name: "Jains Influence Modifier",
        desc: "Modifies to the influence of the Jains estate.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "ESTATES",
        image: "/images/icons/estates.png",
    },
    {
        name: "Jains Loyalty Modifier",
        desc: "Modifies to the loyalty equilibrium of the Jains estate.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "ESTATES",
        image: "/images/icons/estates.png",
    },
    {
        name: "Marathas Influence Modifier",
        desc: "Modifies to the influence of the Marathas estate.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "ESTATES",
        image: "/images/icons/estates.png",
    },
    {
        name: "Marathas Loyalty Modifier",
        desc: "Modifies to the loyalty equilibrium of the Marathas estate.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "ESTATES",
        image: "/images/icons/estates.png",
    },
    {
        name: "Rajputs Influence Modifier",
        desc: "Modifies to the influence of the Rajputs estate.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "ESTATES",
        image: "/images/icons/estates.png",
    },
    {
        name: "Rajputs Loyalty Modifier",
        desc: "Modifies to the loyalty equilibrium of the Rajputs estate.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "ESTATES",
        image: "/images/icons/estates.png",
    },
    {
        name: "Vaishyas Influence Modifier",
        desc: "Modifies to the influence of the Vaishyas estate.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "ESTATES",
        image: "/images/icons/estates.png",
    },
    {
        name: "Vaishyas Loyalty Modifier",
        desc: "Modifies to the loyalty equilibrium of the Vaishyas estate.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "ESTATES",
        image: "/images/icons/estates.png",
    },
    //HRE SECTION
    {
        name: "Imperial Authority",
        desc: "Modifies the impact of imperial authority gains.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "HRE",
        image: "/images/icons/imperial_authority.png",
    },
    {
        name: "Imperial Authority Value",
        desc: "Adds to the rate of imperial authority gained per month.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "HRE",
        image: "/images/icons/imperial_authority.png",
    },
    {
        name: "Free City Imperial Authority",
        desc: "Adds to the rate of imperial authority gained per month from Free Cities.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "HRE",
        image: "/images/icons/imperial_authority.png",
    },
    {
        name: "Imperial Mercenary Cost",
        desc: "Modifies the cost of mercenary companies for nations within the Holy Roman Empire.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "HRE",
        image: "/images/icons/imperial_authority.png",
    },
    {
        name: "Max Free Cities",
        desc: "Adds to the maximum number of free cities allowed.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "HRE",
        image: "/images/icons/imperial_authority.png",
    },
    {
        name: "Max Electors",
        desc: "Adds to the maximum number of electors allowed.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "HRE",
        image: "/images/icons/imperial_authority.png",
    },
    {
        name: "Legitimate Subject Elector",
        desc: "Adds to the elector desire for the current country to become Emperor (if they are a valid choice).",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "HRE",
        image: "/images/icons/imperial_authority.png",
    },
    //STABILITY SECTION
    {
        name: "Global Unrest",
        desc: "Adds to the base unrest value.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "STABILITY",
        image: "/images/icons/stability.png",
    },
    {
        name: "Stability Cost Modifier",
        desc: "Modifies the administrative power cost of raising stability.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "STABILITY",
        image: "/images/icons/stability.png",
    },
    {
        name: "Global Autonomy",
        desc: "Adds to the monthly rate of autonomy in owned provinces.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "STABILITY",
        image: "/images/icons/stability.png",
    },
    {
        name: "Min Autonomy",
        desc: "Sets the minimum autonomy level allowed in all owned provinces.",
        function: "CONSTANT - NUM",
        type: "PERCENTAGE",
        category: "STABILITY",
        image: "/images/icons/stability.png",
    },
    {
        name: "Autonomy Change Time",
        desc: "Modifies the cooldown for the autonomy reduction and increase buttons.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "STABILITY",
        image: "/images/icons/stability.png",
    },
    {
        name: "Harsh Treatment Cost",
        desc: "Modifies the military power cost for using harsh treatment.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "STABILITY",
        image: "/images/icons/stability.png",
    },
    {
        name: "Years Of Nationalism",
        desc: "Adds to the base separatism value of provinces when conquered.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "STABILITY",
        image: "/images/icons/stability.png",
    },
    {
        name: "Min Autonomy In Territories",
        desc: "Modifies the minimum autonomy experienced in territories.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "STABILITY",
        image: "/images/icons/stability.png",
    },
    {
        name: "Unrest Catholic Provinces",
        desc: "Modifies the local unrest in all provinces of the catholic religion",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "STABILITY",
        image: "/images/icons/stability.png",
    },
    //SUBJECT SECTION
    {
        name: "Liberty Desire",
        desc: "Adds to subject liberty desire against their overlord.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "SUBJECT",
        image: "/images/icons/vassalage.png",
    },
    {
        name: "Liberty Desire From Subject Development",
        desc: "Modifies the subject liberty desire from development against their overlord (Note: Tooltip is bugged as of 1.29. A modifier of -0.2 shows as -0.20% when it reduces it by 20%).",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "SUBJECT",
        image: "/images/icons/vassalage.png",
    },
    {
        name: "Reduced Liberty Desire",
        desc: "Adds to the liberty desire subjects have against their overlord. Applied to the overlord.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "SUBJECT",
        image: "/images/icons/vassalage.png",
    },
    {
        name: "Reduced Liberty Desire On Same Continent",
        desc: "Adds to the liberty desire subjects have against their overlord if on the same continent. Applied to the overlord.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "SUBJECT",
        image: "/images/icons/vassalage.png",
    },
    //ESPIONAGE SECTION
    {
        name: "Spy Offence",
        desc: "Modifies the base effectiveness of spies against enemies.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "ESPIONAGE",
        image: "/images/icons/diplomacy_spy_icon.png",
    },
    {
        name: "Global Spy Defence",
        desc: "Modifies the base effectiveness of counter-espionage against enemy spies.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "ESPIONAGE",
        image: "/images/icons/diplomacy_spy_icon.png",
    },
    {
        name: "Discovered Relations Impact",
        desc: "Modifies the relations impact applied to a country when discovered committing an espionage action.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "ESPIONAGE",
        image: "/images/icons/diplomacy_spy_icon.png",
    },
    {
        name: "Rebel Support Efficiency",
        desc: "Modifies the effectiveness of supported rebels in other countries.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "ESPIONAGE",
        image: "/images/icons/diplomacy_spy_icon.png",
    },
    //RELIGION SECTION
    {
        name: "Global Missionary Strength",
        desc: "Adds to the base missionary strength against all religions.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "RELIGION",
        image: "/images/icons/catholic.png",
    },
    {
        name: "Global Heretic Missionary Strength",
        desc: "Adds to the base missionary strength against heretic religions.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "RELIGION",
        image: "/images/icons/catholic.png",
    },
    {
        name: "Missionaries",
        desc: "Adds to the base missionary count for a country.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "RELIGION",
        image: "/images/icons/catholic.png",
    },
    {
        name: "Missionary Maintenance Cost",
        desc: "Modifies the cost of missionary maintenance whilst converting provinces.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "RELIGION",
        image: "/images/icons/catholic.png",
    },
    {
        name: "Religious Unity",
        desc: "Adds to the base religious unity value for a country.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "RELIGION",
        image: "/images/icons/catholic.png",
    },
    {
        name: "Tolerance Own",
        desc: "Adds to the base tolerance for the true faith within a country.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "RELIGION",
        image: "/images/icons/catholic.png",
    },
    {
        name: "Tolerance Heretic",
        desc: "Adds to the base tolerance for heretics within a country.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "RELIGION",
        image: "/images/icons/catholic.png",
    },
    {
        name: "Tolerance Heathen",
        desc: "Adds to the base tolerance for heathens within a country.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "RELIGION",
        image: "/images/icons/catholic.png",
    },
    {
        name: "Papal Influence",
        desc: "Adds to the rate of papal influence gained per year.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "RELIGION",
        image: "/images/icons/catholic.png",
    },
    {
        name: "Church Power Modifier",
        desc: "Modifies the effectiveness of church power gains.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "RELIGION",
        image: "/images/icons/catholic.png",
    },
    {
        name: "Monthly Fervor Increase",
        desc: "Adds to the rate of fervor gained per month.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "RELIGION",
        image: "/images/icons/catholic.png",
    },
    {
        name: "Harmonization Speed",
        desc: "Modifies the rate at which harmonization occurs.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "RELIGION",
        image: "/images/icons/catholic.png",
    },
    {
        name: "Yearly Harmony",
        desc: "Adds to the rate of harmony gained per year.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "RELIGION",
        image: "/images/icons/catholic.png",
    },
    {
        name: "Monthly Piety",
        desc: "Adds to the rate of piety gained per month.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "RELIGION",
        image: "/images/icons/catholic.png",
    },
    {
        name: "Monthly Karma",
        desc: "Adds to the rate of karma gained per month.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "RELIGION",
        image: "/images/icons/catholic.png",
    },
    {
        name: "Enforce Religion Cost",
        desc: "Modifies the war score cost for the Enforce Religion peace term.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "RELIGION",
        image: "/images/icons/catholic.png",
    },
    {
        name: "Prestige Per Development From Conversion",
        desc: "Adds to the prestige bonus gained per development when successfully converting a province to a state religion.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "RELIGION",
        image: "/images/icons/catholic.png",
    },
    {
        name: "Warscore Cost Vs Other Religion",
        desc: "Modifies the war score costs for peace terms whilst in war against countries of a different religion.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "RELIGION",
        image: "/images/icons/catholic.png",
    },
    {
        name: "Establish Order Cost",
        desc: "Modifies the cost for using the ‘Establish Order’ action.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "RELIGION",
        image: "/images/icons/catholic.png",
    },
    {
        name: "Global Religious Conversion Resistance",
        desc: "Adds to conversion resistance from centres of reformation in all provinces.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "RELIGION",
        image: "/images/icons/catholic.png",
    },
    {
        name: "Relation With Heretics",
        desc: "Adds to the opinion modifier between a country and heretic countries.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "RELIGION",
        image: "/images/icons/catholic.png",
    },
    {
        name: "Curia Treasury Contribution",
        desc: "Modifies the amount of treasury contribution to the Curia.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "RELIGION",
        image: "/images/icons/catholic.png",
    },
    {
        name: "Curia Powers Cost",
        desc: "Modifies the papal influence cost of the curia actions.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "RELIGION",
        image: "/images/icons/catholic.png",
    },
    {
        name: "Yearly Patriarch Authority",
        desc: "Adds to the amount of yearly patriarch authority gained.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "RELIGION",
        image: "/images/icons/catholic.png",
    },
    //COLONIZATION
    {
        name: "Colonists",
        desc: "Modifies the base colonist count for a country.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "COLONIZATION",
        image: "/images/icons/global_settler_increase.png",
    },
    {
        name: "Colonist Placement Chance",
        desc: "Adds to the base colonial placement chance for colonists, which is the chance that additional settlers will be spawned whilst the colonist is present.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "COLONIZATION",
        image: "/images/icons/global_settler_increase.png",
    },
    {
        name: "Global Colonial Growth",
        desc: "Adds to the base yearly colonial growth gain.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "COLONIZATION",
        image: "/images/icons/global_settler_increase.png",
    },
    {
        name: "Range",
        desc: "Modifies the base colonisation range, used for exploration, colonisation and coring province that border sea.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "COLONIZATION",
        image: "/images/icons/global_settler_increase.png",
    },
    {
        name: "Native Uprising Chance",
        desc: "Adds to the chance of native uprisings in a colony province.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "COLONIZATION",
        image: "/images/icons/global_settler_increase.png",
    },
    {
        name: "Native Assimilation",
        desc: "Modifies the bonus from assimilation in colonies. Native assimilation is bonus to goods produced depends on the native population.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "COLONIZATION",
        image: "/images/icons/global_settler_increase.png",
    },
    {
        name: "Migration Cooldown",
        desc: "Modifies the cooldown for the migration action for primitive nations that can migrate.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "COLONIZATION",
        image: "/images/icons/global_settler_increase.png",
    },
    {
        name: "Global Tariffs",
        desc: "Modifies the tariff income from colonial nations.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "COLONIZATION",
        image: "/images/icons/global_settler_increase.png",
    },
    {
        name: "Treasure Fleet Income",
        desc: "Modifies the income from treasure fleets sent by colonial nations.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "COLONIZATION",
        image: "/images/icons/global_settler_increase.png",
    },
    {
        name: "Expel Minorities Cost",
        desc: "Modifies the cost of using the ‘Expel Minorities’ action.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "COLONIZATION",
        image: "/images/icons/global_settler_increase.png",
    },
    //TRADE SECTION
    {
        name: "Caravan Power",
        desc: "Modifies the bonus trade power inland nodes receive from trade power sources.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "TRADE",
        image: "/images/icons/trade_value_modifier.png",
    },
    {
        name: "Merchants",
        desc: "Adds to the base merchant count for a country.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "TRADE",
        image: "/images/icons/trade_value_modifier.png",
    },
    {
        name: "Placed Merchant Power",
        desc: "Modifies the additional trade power when a merchant present in a trade node.",
        function: "ADDITIVE",
        type: "WHOLE NUMBER",
        category: "TRADE",
        image: "/images/icons/trade_value_modifier.png",
    },
    {
        name: "Global Trade Power",
        desc: "Modifies the trade power in all trade nodes for a country.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "TRADE",
        image: "/images/icons/trade_value_modifier.png",
    },
    {
        name: "Global Foreign Trade Power",
        desc: "Modifies the trade power for a country in trade nodes that are not [[Trade#Domestic_trade_power|domestic]].",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "TRADE",
        image: "/images/icons/trade_value_modifier.png",
    },
    {
        name: "Global Own Trade Power",
        desc: "Modifies the trade power for a country in trade nodes that are [[Trade#Domestic_trade_power|domestic]].",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "TRADE",
        image: "/images/icons/trade_value_modifier.png",
    },
    {
        name: "Global Province Trade Power Modifier",
        desc: "Modifies the base trade power of owned provinces.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "TRADE",
        image: "/images/icons/trade_value_modifier.png",
    },
    {
        name: "Global Trade Goods Size Modifier",
        desc: "Modifies the base trade good size of owned provinces.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "TRADE",
        image: "/images/icons/trade_value_modifier.png",
    },
    {
        name: "Trade Efficiency",
        desc: "Modifies a country's trade income. (Maximum is 200%)",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "TRADE",
        image: "/images/icons/trade_value_modifier.png",
    },
    {
        name: "Trade Range Modifier",
        desc: "Modifies the trade range used to determine if a country can place a merchant in a trade node.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "TRADE",
        image: "/images/icons/trade_value_modifier.png",
    },
    {
        name: "Trade Steering",
        desc: "Modifies the bonus to trade power used for steering when determining which outgoing node trade is steered to. If you have a merchant present, it also slightly increases the outgoing value.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "TRADE",
        image: "/images/icons/trade_value_modifier.png",
    },
    {
        name: "Global Ship Trade Power",
        desc: "Modifies the trade power ships grant when protecting trade.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "TRADE",
        image: "/images/icons/trade_value_modifier.png",
    },
    {
        name: "Privateer Efficiency",
        desc: "Modifies the effectiveness of privateers in a trade node.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "TRADE",
        image: "/images/icons/trade_value_modifier.png",
    },
    {
        name: "Embargo Efficiency",
        desc: "Modifies the effectiveness of embargoing another country.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "TRADE",
        image: "/images/icons/trade_value_modifier.png",
    },
    {
        name: "Ship Power Propagation",
        desc: "Modifies the propagation of trade power from ships protecting trade.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "TRADE",
        image: "/images/icons/trade_value_modifier.png",
    },
    {
        name: "Center Of Trade Upgrade Cost",
        desc: "Modifies the cost of upgrading a center of trade in a province.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "TRADE",
        image: "/images/icons/trade_value_modifier.png",
    },
    {
        name: "Trade Company Investment Cost",
        desc: "Modifies the cost of purchasing a trade company investment in a state.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "TRADE",
        image: "/images/icons/trade_value_modifier.png",
    },
    {
        name: "Mercantilism Cost",
        desc: "Modifies the cost of the ‘Boost Mercantilism’ action.",
        function: "MULTIPLICATIVE",
        type: "PERCENTAGE",
        category: "TRADE",
        image: "/images/icons/trade_value_modifier.png",
    }
]

export const modifierVals = {
    army_tradition: 0,
    army_tradition_decay: 0,
    army_tradition_from_battle: 0,
    yearly_army_professionalism: 0,
    drill_gain_modifier: 0,
    drill_decay_modifier: 0,
    infantry_cost: 0,
    infantry_power: 0,
    infantry_fire: 0,
    infantry_shock: 0,
    cavalry_cost: 0,
    cavalry_power: 0,
    cavalry_fire: 0,
    cavalry_shock: 0,
    artillery_cost: 0,
    artillery_power: 0,
    artillery_fire: 0,
    artillery_shock: 0,
    cav_to_inf_ratio: 0,
    cavalry_flanking: 0,
    artillery_bonus_vs_fort: 0,
    backrow_artillery_damage: 0,
    discipline: 0,
    mercenary_discipline: 0,
    land_morale: 0,
    defensiveness: 0,
    siege_ability: 0,
    movement_speed: 0,
    fire_damage: 0,
    fire_damage_received: 0,
    shock_damage: 0,
    shock_damage_received: 0,
    recover_army_morale_speed: 0,
    siege_blockade_progress: 0,
    reserves_organisation: 0,
    land_attrition: 0,
    reinforce_cost_modifier: 0,
    reinforce_speed: 0,
    manpower_recovery_speed: 0,
    global_manpower: 0,
    global_manpower_modifier: 0,
    global_regiment_cost: 0,
    global_regiment_recruit_speed: 0,
    global_supply_limit_modifier: 0,
    land_forcelimit: 0,
    land_forcelimit_modifier: 0,
    land_maintenance_modifier: 0,
    mercenary_cost: 0,
    merc_maintenance_modifier: 0,
    possible_condottieri: 0,
    hostile_attrition: 0,
    garrison_size: 0,
    global_garrison_growth: 0,
    fort_maintenance_modifier: 0,
    rival_border_fort_maintenance: 0,
    war_exhaustion: 0,
    war_exhaustion_cost: 0,
    leader_land_fire: 0,
    leader_land_manuever: 0,
    leader_land_shock: 0,
    leader_siege: 0,
    general_cost: 0,
    free_leader_pool: 0,
    raze_power_gain: 0,
    loot_amount: 0,
    available_province_loot: 0,
    prestige_from_land: 0,
    amount_of_banners: 0,
    war_taxes_cost_modifier: 0,
    leader_cost: 0,
    may_recruit_female_generals: false,
    special_unit_forcelimit: 0,
    manpower_in_true_faith_provinces: 0,
    mercenary_manpower: 0,
    navy_tradition: 0,
    navy_tradition_decay: 0,
    naval_tradition_from_battle: 0,
    naval_tradition_from_trade: 0,
    heavy_ship_cost: 0,
    heavy_ship_power: 0,
    light_ship_cost: 0,
    light_ship_power: 0,
    galley_cost: 0,
    galley_power: 0,
    transport_cost: 0,
    transport_power: 0,
    global_ship_cost: 0,
    global_ship_recruit_speed: 0,
    global_ship_repair: 0,
    naval_forcelimit: 0,
    naval_forcelimit_modifier: 0,
    naval_maintenance_modifier: 0,
    global_sailors: 0,
    global_sailors_modifier: 0,
    sailor_maintenance_modifer: 0,
    sailors_recovery_speed: 0,
    blockade_efficiency: 0,
    capture_ship_chance: 0,
    global_naval_engagement_modifier: 0,
    naval_attrition: 0,
    naval_morale: 0,
    ship_durability: 0,
    sunk_ship_morale_hit_recieved: 0,
    recover_navy_morale_speed: 0,
    prestige_from_naval: 0,
    leader_naval_fire: 0,
    leader_naval_manuever: 0,
    leader_naval_shock: 0,
    own_coast_naval_combat_bonus: 0,
    admiral_cost: 0,
    movement_speed_onto_off_boat_modifier: 0,
    global_naval_barrage_cost: 0,
    allowed_marine_fraction: 0,
    flagship_cost: 0,
    may_perform_slave_raid: false,
    may_perform_slave_raid_on_same_religion: false,
    admiral_skill_gain_modifier: 0,
    flagship_durability: 0,
    flagship_morale: 0,
    flagship_naval_engagement_modifier: 0,
    flagship_landing_penalty: 0,
    number_of_cannons_flagship_modifier: 0,
    naval_maintenance_flagship_modifier: 0,
    trade_power_in_fleet_modifier: 0,
    morale_in_fleet_modifier: 0,
    blockade_impact_on_siege_in_fleet_modifier: 0,
    exploration_mission_range_in_fleet_modifier: 0,
    barrage_cost_in_fleet_modifier: 0,
    naval_attrition_in_fleet_modifier: 0,
    privateering_efficiency_in_fleet_modifier: 0,
    prestige_from_battles_in_fleet_modifier: 0,
    naval_tradition_in_fleet_modifier: 0,
    cannons_for_hunting_pirates_in_fleet: 0,
    movement_speed_in_fleet_modifier: 0,
    diplomats: 0,
    diplomatic_reputation: 0,
    diplomatic_upkeep: 0,
    envoy_travel_time: 0,
    fabricate_claims_cost: 0,
    improve_relation_modifier: 0,
    vassal_forcelimit_bonus: 0,
    vassal_income: 0,
    ae_impact: 0,
    claim_duration: 0,
    diplomatic_annexation_cost: 0,
    province_warscore_cost: 0,
    unjustified_demands: 0,
    enemy_core_creation: 0,
    rival_change_cost: 0,
    justify_trade_conflict_cost: 0,
    stability_cost_to_declare_war: 0,
    global_tax_income: 0,
    global_tax_modifier: 0,
    production_efficiency: 0,
    state_maintenance_modifier: 0,
    inflation_action_cost: 0,
    inflation_reduction: 0,
    interest: 0,
    development_cost: 0,
    build_cost: 0,
    build_time: 0,
    administrative_efficiency: 0,
    core_creation: 0,
    core_decay_on_your_own: 0,
    admin_tech_cost_modifier: 0,
    diplomatic_tech_cost_modifier: 0,
    military_tech_cost_modifier: 0,
    technology_cost: 0,
    idea_cost: 0,
    embracement_cost: 0,
    global_institution_spread: 0,
    institution_spread_from_true_faith: 0,
    native_advancement_cost: 0,
    all_power_cost: 0,
    innovativeness_gain: 0,
    free_adm_policy: 0,
    free_dip_policy: 0,
    free_mil_policy: 0,
    possible_adm_policy: 0,
    possible_dip_policy: 0,
    possible_mil_policy: 0,
    possible_policy: 0,
    free_policy: 0,
    country_admin_power: 0,
    country_diplomatic_power: 0,
    country_military_power: 0,
    prestige: 0,
    prestige_decay: 0,
    monthly_splendor: 0,
    yearly_corruption: 0,
    advisor_cost: 0,
    advisor_pool: 0,
    female_advisor_chance: 0,
    heir_chance: 0,
    monarch_admin_power: 0,
    fixed: 0,
    monarch_diplomatic_power: 0,
    fixed: 0,
    monarch_military_power: 0,
    fixed: 0,
    adm_advisor_cost: 0,
    dip_advisor_cost: 0,
    mil_advisor_cost: 0,
    monthly_support_heir_gain: 0,
    power_projection_from_insults: 0,
    yearly_absolutism: 0,
    max_absolutism: 0,
    legitimacy: 0,
    Does: 0,
    republican_tradition: 0,
    Does: 0,
    devotion: 0,
    Does: 0,
    horde_unity: 0,
    Does: 0,
    meritocracy: 0,
    monthly_militarized_society: 0,
    yearly_tribal_allegiance: 0,
    _influence: 0,
    _influence: 0,
    Generated: 0,
    imperial_mandate: 0,
    election_cycle: 0,
    candidate_random_bonus: 0,
    reelection_cost: 0,
    reform_progress_growth: 0,
    governing_capacity: 0,
    governing_capacity_modifier: 0,
    state_governing_cost: 0,
    trade_company_governing_cost: 0,
    expand_administration_cost: 0,
    yearly_revolutionary_zeal: 0,
    max_revolutionary_zeal: 0,
    Burghers_influence_modifier: 0,
    Clergy_influence_modifier: 0,
    Nobility_influence_modifier: 0,
    Cossacks_influence_modifier: 0,
    Dhimmi_influence_modifier: 0,
    tribes_influence_modifier: 0,
    Brahmins_influence_modifier: 0,
    Jains_influence_modifier: 0,
    Marathas_influence_modifier: 0,
    Rajputs_influence_modifier: 0,
    Vaishyas_influence_modifier: 0,
    Burghers_loyalty_modifier: 0,
    Clergy_loyalty_modifier: 0,
    Nobility_loyalty_modifier: 0,
    Cossacks_loyalty_modifier: 0,
    Dhimmi_loyalty_modifier: 0,
    Tribes_loyalty_modifier: 0,
    Brahmins_loyalty_modifier: 0,
    Jains_loyalty_modifier: 0,
    Marathas_loyalty_modifier: 0,
    Rajputs_loyalty_modifier: 0,
    Vaishyas_loyalty_modifier: 0,
    imperial_authority: 0,
    imperial_authority_value: 0,
    free_city_imperial_authority: 0,
    imperial_mercenary_cost: 0,
    max_free_cities: 0,
    max_electors: 0,
    legitimate_subject_elector: 0,
    culture_conversion_cost: 0,
    num_accepted_cultures: 0,
    same_culture_advisor_cost: 0,
    promote_culture_cost: 0,
    global_unrest: 0,
    stability_cost_modifier: 0,
    global_autonomy: 0,
    min_autonomy: 0,
    autonomy_change_time: 0,
    harsh_treatment_cost: 0,
    years_of_nationalism: 0,
    min_autonomy_in_territories: 0,
    unrest_catholic_provinces: 0,
    liberty_desire: 0,
    liberty_desire_from_subject_development: 0,
    reduced_liberty_desire: 0,
    reduced_liberty_desire_on_same_continent: 0,
    spy_offence: 0,
    global_spy_defence: 0,
    discovered_relations_impact: 0,
    rebel_support_efficiency: 0,
    global_missionary_strength: 0,
    global_heretic_missionary_strength: 0,
    missionaries: 0,
    missionary_maintenance_cost: 0,
    religious_unity: 0,
    tolerance_own: 0,
    tolerance_heretic: 0,
    tolerance_heathen: 0,
    papal_influence: 0,
    church_power_modifier: 0,
    monthly_fervor_increase: 0,
    harmonization_speed: 0,
    yearly_harmony: 0,
    monthly_piety: 0,
    monthly_karma: 0,
    enforce_religion_cost: 0,
    prestige_per_development_from_conversion: 0,
    warscore_cost_vs_other_religion: 0,
    establish_order_cost: 0,
    global_religious_conversion_resistance: 0,
    relation_with_heretics: 0,
    curia_treasury_contribution: 0,
    curia_powers_cost: 0,
    yearly_patriarch_authority: 0,
    cb_on_religious_enemies: 0,
    cb_on_religious_enemies: 0,
    colonists: 0,
    colonist_placement_chance: 0,
    global_colonial_growth: 0,
    range: 0,
    native_uprising_chance: 0,
    native_assimilation: 0,
    migration_cooldown: 0,
    global_tariffs: 0,
    treasure_fleet_income: 0,
    expel_minorities_cost: 0,
    caravan_power: 0,
    merchants: 0,
    placed_merchant_power: 0,
    global_trade_power: 0,
    global_foreign_trade_power: 0,
    global_own_trade_power: 0,
    global_prov_trade_power_modifier: 0,
    global_trade_goods_size_modifier: 0,
    trade_efficiency: 0,
    trade_range_modifier: 0,
    trade_steering: 0,
    global_ship_trade_power: 0,
    privateer_efficiency: 0,
    embargo_efficiency: 0,
    ship_power_propagation: 0,
    center_of_trade_upgrade_cost: 0,
    trade_company_investment_cost: 0,
    mercantilism_cost: 0,
}

const modifierLength = modifiers.length;

export {modifierLength}